# Project configuration for Supabase CLI
project_id = ""

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

# Functions configuration with proper nesting
[functions]
serve = { port = 8000 }