name: Deploy to Production

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy-db:
    name: Deploy Supabase Schema to Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for comparing changes
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      - name: Check for migration changes since last production deployment
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            supabase/migrations/**
            supabase/functions/**
            supabase/triggers/**
            supabase/policies/**
          since_last_remote_commit: true
      
      - name: Apply migrations to production
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Detected changes in Supabase files, preparing for production deployment..."
          
          # Show preview of changes that will be applied
          echo "Changes to be applied:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "- $file"
          done
          
          # Link to the Supabase production project
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID_PROD }} --password ${{ secrets.SUPABASE_DB_PASSWORD_PROD }}
          
          # Push database changes in dry-run mode first (preview only)
          echo "Running migration preview..."
          supabase db push --dry-run
          
          # If we get here, apply the changes for real
          echo "Applying migrations to production database..."
          supabase db push
          
          # Verify migrations were applied correctly
          echo "Verifying migrations..."
          supabase db remote changes
        
      - name: Deploy Edge Functions (if any)
        if: contains(steps.changed-files.outputs.all_changed_files, 'supabase/functions/')
        run: |
          # Deploy all edge functions that have changed
          echo "Deploying Edge Functions to production..."
          supabase functions deploy
          
      - name: Report Database Deployment Status
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅' || '❌' }} Production database deployment: ${{ job.status }}\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nBy: ${{ github.actor }}${{ steps.changed-files.outputs.any_changed == 'true' && '\n\nChanges applied:\n' || '\n\nNo database changes detected.' }}${{ steps.changed-files.outputs.any_changed == 'true' && steps.changed-files.outputs.all_changed_files || '' }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_PROD_DEPLOYMENTS }}

  build-and-deploy-frontend:
    name: Deploy Frontend App to Production
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-db
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        working-directory: ./src
          
      - name: Create .env file
        run: |
          cat > ./src/.env.production << EOF
          REACT_APP_SUPABASE_URL=${{ secrets.SUPABASE_URL_PROD }}
          REACT_APP_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY_PROD }}
          REACT_APP_API_URL=${{ secrets.AZURE_FUNCTIONS_URL_PROD }}
          EOF
          
      - name: Build
        run: npm run build
        working-directory: ./src
          
      - name: Deploy to Azure Static Web Apps
        id: deploy-to-azure-static-web-apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/build"  # Location of built files
          skip_app_build: true  # We've already built the app
          
      - name: Report Deployment Status
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ steps.deploy-to-azure-static-web-apps.outcome == 'success' && '✅' || '❌' }} Production frontend deployment: ${{ steps.deploy-to-azure-static-web-apps.outcome }}\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nBy: ${{ github.actor }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_PROD_DEPLOYMENTS }}

  deploy-azure-functions:
    name: Deploy Azure Functions to Production
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-db
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/api
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./src/api
        
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: ./src/api
        
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-azure-functions
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME_PROD }}
          package: './src/api/publish'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PROD }}
          
      - name: Report Deployment Status
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ steps.deploy-to-azure-functions.outcome == 'success' && '✅' || '❌' }} Production Azure Functions deployment: ${{ steps.deploy-to-azure-functions.outcome }}\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nBy: ${{ github.actor }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_PROD_DEPLOYMENTS }}
          
  post-deployment-verification:
    name: Production Post-Deployment Verification
    runs-on: ubuntu-latest
    environment: production
    needs: [build-and-deploy-frontend, deploy-azure-functions]
    steps:
      - name: Check Frontend Deployment
        run: |
          # Wait a moment for deployment to stabilize
          sleep 60
          
          # Check if the frontend is accessible
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.FRONTEND_URL_PROD }})
          
          if [ $HTTP_STATUS -eq 200 ]; then
            echo "Frontend deployment successful with HTTP status $HTTP_STATUS"
          else
            echo "Frontend deployment check failed with HTTP status $HTTP_STATUS"
            exit 1
          fi
          
      - name: Check Azure Functions
        run: |
          # Wait a moment for deployment to stabilize
          sleep 60
          
          # Check if the API is accessible (health check endpoint)
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.AZURE_FUNCTIONS_URL_PROD }}/api/health)
          
          if [ $HTTP_STATUS -eq 200 ]; then
            echo "Azure Functions deployment successful with HTTP status $HTTP_STATUS"
          else
            echo "Azure Functions deployment check failed with HTTP status $HTTP_STATUS"
            exit 1
          fi
          
      - name: Report Verification Status
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅' || '❌' }} Production deployment verification: ${{ job.status }}\nAll systems are operational and responding correctly."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_PROD_DEPLOYMENTS }}
